---
title: "explore drd"
author: 'Anisha Bhattarai'
date: "2026-06-30"
output: html_document
---

<!-- 
WIMD has published six times since 2005(2005, 2008, 2011, 2014, 2019, 2025) which tracks top 50 most deprived areas on those six releases. It explores dataset alone and ahead of joining to rural urban status -->
```{r setup,message=FALSE,warning=FALSE}
library(tidyverse)
library(janitor)
library(readODS)

```

## Step 1- Loading and cleaning DRD  data
```{r load_drd_data}
drd_WIMD <- suppressWarnings(read_ods(
  "../data/raw/welsh-index-of-multiple-deprivation-wimd-2025-data-underlying-deep-dooted-deprivation-analysis.ods",
  sheet = "Data",
  skip = 4))%>% 
  clean_names() %>%
  filter(!is.na(.[[3]])) # col 3 = lsoa_code
cat("Rows:", nrow(drd_WIMD), "| Cols:", ncol(drd_WIMD), "\n")
# Historic rank cols use  "[x]" for suppressed value(boundary change in WIMD publications )
# str_remove_all("^0-9]") strip non numeric:"[x]"-> NA
rank_cols <- names(drd_WIMD)[5:10]
drd <- drd_WIMD %>%
  mutate(across(all_of(rank_cols),
                ~as.numeric(str_remove_all(as.character(.x), "[^0-9]"))))

```

## Step 2- Persistent four categories: Never/Sometimes/Often/ Deep-rooted
```{r category}
# four persistent categories- LSOAs in each
drd %>% count(category_of_deep_rooted_deprivation, sort = TRUE)
```

## Step 3- Check suppressed values as boundary change not missing data
```{r suppressed}
cat("Suppressed/missing values per rank column:\n")
colSums(is.na(drd[ranks_cols]))
```

## Step 4- Persistently deprived areas in local authorities
```{r persistent}
# LA persistently deprived LSOAs
drd %>%
  filter(category_of_deep_rooted_deprivation !=
           "LSOAs never ranked in top 50 most deprived") %>%
  count(local_authority, category_of_deep_rooted_deprivation) %>%
  pivot_wider(names_from = category_of_deep_rooted_deprivation,
              values_from = n, values_fill = 0)
    
```

## Step 5- Rank volatility: areas rank move over 20 years
```{r volatility}
# rank volatility= SD across all 6 publication of WIMD
drd <- drd %>%
  rowwise() %>%
  mutate(rank_sd = sd(c_across(all_of(rank_cols)), na.rm = TRUE)) %>%
  ungroup()

summary(drd$rank_sd)

```

## Step 6- Most stable rank areas 
```{r most_stable}
# most stable should be deep rooted LSOA. lowest rank_sd barely moves 
drd %>%
  arrange(rank_sd) %>%
  select(local_authority, lower_layer_super_output_area_lsoa,
         category_of_deep_rooted_deprivation, rank_sd) %>%
  head(10)


```

