---
title: "Explore RUC data"
author: 'Anisha Bhattarai'
date: "2026-06-30"
output: html_document
---
<!-- This Script explore ONS Rural Urban classification 2021
-->
```{r setup, message=FALSE, warning=FALSE}
library(tidyverse)
library(readODS)
library(janitor)
```

## Step 1- Load RUC file, Welsh LSOAs only
```{r load_ruc}
ruc_files <- list.files("../data/raw", pattern = "Rural", full.names = TRUE)
ruc <- read_csv(ruc_files[1]) %>%
  clean_names() %>%
  filter(str_starts(lsoa21cd, "W"))   # only welsh

cat("Welsh LSOAs:", nrow(ruc), "\n")
names(ruc)

```

## Step 2- Basic Rural/Urban split
```{r split_binary}
ruc %>%
  count(urban_rural_flag) %>%
  mutate(pct = round(100 * n / sum(n), 1))

```

## Step 3- Six RUC categories 
```{r categories}
# RUC 6 categories: Urban/Larger, rural/ smaller rural each area split nearer to further from major city 
ruc %>%
  count(ruc21nm, urban_rural_flag) %>%
  arrange(urban_rural_flag, desc(n))

```

## Join WIMD local authority names and find most rural LAs 
```{r la_rural_pct}
# LAs most rural, join rank to get LA names by joining to rank data
ranks_la <- read_ods(
  "../data/raw/wimd-2025-index-and-domain-ranks-by-small-area.ods",
  sheet = "WIMD_2025_ranks", skip = 2
) %>%
  clean_names() %>%
  select(where(~!all(is.na(.)))) %>%
  select(lsoa_code, local_authority_name_eng)

ruc %>%
  left_join(ranks_la, by = c("lsoa21cd" = "lsoa_code")) %>%
  group_by(local_authority_name_eng) %>%
  summarise(
    total     = n(),
    rural     = sum(urban_rural_flag == "Rural"),
    pct_rural = round(100 * rural / total, 1),
    .groups   = "drop"
  ) %>%
  arrange(desc(pct_rural)) %>%
  print(n = 22)


```

## Step 5 - within rural area how many "further from" and "nearer to" a town
```{r remoteness_split}
# within rural, further vs near from major town
ruc %>%
  filter(urban_rural_flag == "Rural") %>%
  mutate(type = if_else(str_detect(ruc21nm, "Further"),
                        "Further from town", "Nearer to town")) %>%
  count(type) %>%
  mutate(pct = round(100 * n / sum(n), 1))


```

## Step 6- Four local authority RUC category breakdown
```{r case_study}
ranks_la %>%
  filter(local_authority_name_eng %in% c("Powys", "Ceredigion", "Pembrokeshire", "Swansea")) %>%
  count(local_authority_name_eng, lsoa_code) %>%
  pivot_wider(
    names_from  = local_authority_name_eng,
    values_from = n,
    values_fill = 0
  )
```

