---
title: "explore drd"
author: 'Student ID: 52533934'
date: "2026-06-30"
output: html_document
---

```{r setup,message=FALSE,warning=FALSE}
library(tidyverse)
library(janitor)
library(readODS)

```


```{r}
drd_WIMD <- suppressWarnings(read_ods(
  "../data/raw/welsh-index-of-multiple-deprivation-wimd-2025-data-underlying-deep-dooted-deprivation-analysis.ods",
  sheet = "Data",
  skip = 4))%>% 
  clean_names() %>%
  filter(!is.na(.[[3]])) # col 3 = lsoa_code
cat("Rows:", nrow(drd_WIMD), "| Cols:", ncol(drd_WIMD), "\n")
# Historic rank has "[x]" for suppressed value(boundary change)
# str_remove_all("^0-9]") strip non numeric:"[x]"-> NA
rank_cols <- names(drd_WIMD)[5:10]
drd <- drd_WIMD %>%
  mutate(across(all_of(rank_cols),
                ~as.numeric(str_remove_all(as.character(.x), "[^0-9]"))))

```

```{r category}
# four persistent categories- LSOAs in each
drd %>% count(category_of_deep_rooted_deprivation, sort = TRUE)
```

```{r suppressed}
# suppressed value by year- boundary change no missing data
colSums(is.na(drd[rank_cols]))

```

```{r }

```

```{r}
cat("Suppressed/missing values per rank column:\n")
colSums(is.na(drd_WIMD[ranks_cols]))
```

```{r persistent}
# LA persistently deprived LSOAs
drd %>%
  filter(category_of_deep_rooted_deprivation !=
           "LSOAs never ranked in top 50 most deprived") %>%
  count(local_authority, category_of_deep_rooted_deprivation) %>%
  pivot_wider(names_from = category_of_deep_rooted_deprivation,
              values_from = n, values_fill = 0)

    
```

```{r volatility}
# rank volatility= SD across all variable iteration
drd <- drd %>%
  rowwise() %>%
  mutate(rank_sd = sd(c_across(all_of(rank_cols)), na.rm = TRUE)) %>%
  ungroup()

summary(drd$rank_sd)


```

```{r most_stable}
# most stable should be deep rooted LSOA
drd %>%
  arrange(rank_sd) %>%
  select(local_authority, lower_layer_super_output_area_lsoa,
         category_of_deep_rooted_deprivation, rank_sd) %>%
  head(10)


```




```{r}
rank_cols <- c("wimd_2025_rank", "wimd_2019_rank", "wimd_2014_rank",
               "wimd_2011_rank", "wimd_2008_rank", "wimd_2005_rank")

drd_WIMD <- drd_WIMD %>%
  rowwise() %>%
  mutate(rank_sd = sd(c_across(all_of(rank_cols)), na.rm = TRUE)) %>%
  ungroup()

cat("Volatility summary (SD of WIMD ranks across all available iterations):\n")
summary(drd_WIMD$rank_sd)

```

```{r}
drd_WIMD %>%
  arrange(desc(rank_sd)) %>%
  select(local_authority, lower_layer_super_output_area_lsoa, rank_sd) %>%
  head(10)

```
```{r}
drd_WIMD %>%
  arrange(rank_sd) %>%
  select(local_authority, lower_layer_super_output_area_lsoa, rank_sd) %>%
  head(10)

```

```{r}
drd_WIMD %>%
  arrange(rank_sd) %>%
  select(local_authority, lower_layer_super_output_area_lsoa,
         category_of_deep_rooted_deprivation, rank_sd) %>%
  head(10)

```

