---
title: "Masterdata"
author: 'Student ID: 52533934'
date: "2026-07-01"
output: html_document
---

```{r setup, message=FALSE, warning=FALSE}
library(tidyverse)
library(janitor)
library(readODS)

```


```{r load_all_data}
ranks_WIMD <- read_ods(
  "../data/raw/wimd-2025-index-and-domain-ranks-by-small-area.ods",
  sheet = "WIMD_2025_ranks",
  skip  = 2
) %>%
  clean_names() %>%
  select(where(~!all(is.na(.)))) %>%      # drop empty column (col 13)
  mutate(across(4:12, as.numeric)) %>%
  filter(!is.na(lsoa_code)) %>%
  rename(la_name = local_authority_name_eng, lsoa_name = lsoa_name_eng,
         wimd_2025_rank = wimd_2025, income_rank = income,
         employment_rank = employment, health_rank = health,
         education_rank = education, access_rank = access_to_services,
         housing_rank = housing, community_safety_rank = community_safety,
         physical_env_rank = physical_environment)

```
```{r}
scores_WIMD <- read_ods(
  "../data/raw/wimd-2025-index-and-domain-scores-by-small-area.ods",
  sheet = "Data",
  skip  = 3
) %>%
  clean_names() %>%
  mutate(across(4:12, as.numeric)) %>%
  filter(!is.na(lsoa_code))%>%
  select(-lsoa_name, -local_authority_name) %>%
  rename(wimd_2025_score = wimd_2025, income_score = income,
         employment_score = employment, health_score = health,
         education_score = education, access_score = access_to_services,
         housing_score = housing, community_safety_score = community_safety,
         physical_env_score = physical_environment)


```

```{r}
drd_history <- c("wimd_2025_rank", "wimd_2019_rank", "wimd_2014_rank",
                   "wimd_2011_rank", "wimd_2008_rank", "wimd_2005_rank")

drd_WIMD <- read_ods(
  "../data/raw/welsh-index-of-multiple-deprivation-wimd-2025-data-underlying-deep-dooted-deprivation-analysis.ods",
  sheet = "Data",
  skip  = 4
) %>%
  clean_names() %>%
  filter(!is.na(lsoa_code)) %>%
  mutate(across(
    all_of(drd_history),
    ~as.numeric(str_remove_all(as.character(.x), "[^0-9]"))
    # converts "[x]" suppression markers to NA
  ))%>%
  select(lsoa_code,
         drd_category = category_of_deep_rooted_deprivation,
         wimd_2019_rank, wimd_2014_rank, wimd_2011_rank,
         wimd_2008_rank, wimd_2005_rank)


```

```{r}
ruc_file <- list.files("../data/raw", pattern = "Rural_Urban", full.names = TRUE)

ruc_WIMD <- read_csv(ruc_file[1]) %>%
  clean_names() %>%
  filter(str_starts(lsoa21cd, "W")) %>%       # Welsh LSOAs only 
  select(lsoa_code = lsoa21cd, ruc_code = ruc21cd,
         ruc_name = ruc21nm, rural_urban = urban_rural_flag)


```
```{r build_master_data}
master <- ranks_WIMD %>%
  left_join(scores_WIMD, by = "lsoa_code") %>%
  left_join(drd_WIMD,    by = "lsoa_code") %>%
  left_join(ruc_WIMD,    by = "lsoa_code") %>%
  mutate(
    # Negative gap = LSOA more deprived on that domain than overall rank shows
    access_rank_gap  = access_rank  - wimd_2025_rank,
    housing_rank_gap = housing_rank - wimd_2025_rank,
    rural_urban  = factor(rural_urban, levels = c("Rural","Urban")),
    drd_category = factor(drd_category,
      levels = c("LSOAs never ranked in top 50 most deprived",
                 "LSOAs sometimes in the top 50 most deprived",
                 "LSOAs often in the top 50 most deprived",
                 "LSOAs in Deep-rooted deprivation"), ordered = TRUE)
  )

cat("Master:", nrow(master), "rows |", ncol(master), "cols\n")

```


```{r validate_data}
# check before stage 4 validating
cat("Duplicates:", sum(duplicated(master$lsoa_code)), "(expected 0)\n")
cat("Rural:", sum(master$rural_urban=="Rural"),
    "| Urban:", sum(master$rural_urban=="Urban"), "\n")
na_check <- colSums(is.na(master))
print(na_check[na_check > 0])
 

```
```{r save}
write_csv(master, "../data/processed/master_dataset.csv")
cat("Saved to ../data/processed/master_dataset.csv\n")


```






```{r}
glimpse(master)
```

